sudo: required
services:
  - docker

before_install:
  - docker build -t hnngo/simple-react-node-with-docker -f Dockerfile.dev .

script:
 - docker run -e CI=true hnngo/simple-react-node-with-docker npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-east-2" 
  app: "simple-react-node-with-docker"
  env: "SimpleReactNodeWithDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-601657596403"
  bucket_path: "simple-react-node-with-docker"
  on:
    branch: master