FROM ubuntu:bionic

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN npm cache clean -f
RUN npm install -g n
RUN n stable

WORKDIR /app

COPY package.json .
RUN npm install
COPY . .

CMD ["npm", "run", "start"]

# docker build -f Dockerfile.dev .
